name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.6.5", "8.8.1", "8.10.1"]
        cabal: ["3.2"]

    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@preview
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages

    - uses: actions/cache@preview
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --write-ghc-environment-files=always -j2
        cabal v2-build --only-dependencies

    - name: Build & test
      run: |
        cabal v2-build
        cabal v2-configure
        cabal v2-test
