name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        cabal -V
        cabal update
        cabal install Cabal cabal-install
        cabal --version
        cabal new-install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal new-configure --enable-tests
        cabal new-build
    - name: Run tests
      run: cabal new-test
